language: php

php:
    - 8.1

services:
  - docker

install:
  - travis_retry composer install # This is a crutch to use travis tokens for github API instead of needing our own
  # Commented out for efficiency reasons
  # - travis_retry make install-php

before_script:
  - echo "APP_ENV=dev" > .env

script:
  - make default-config
  - make clear
  - make ci-with-coverage
  - make install-php COMPOSER_FLAGS="--no-dev -q" # Remove dev dependencies to make sure PHPStan creates errors if prod code depends on dev classes
  - docker run -v $PWD:/app --rm  registry.gitlab.com/fun-tech/fundraising-frontend-docker/php-8.1:stan analyse --level 5 --no-progress cli/ src/ # Can't use "make stan" it contains the test directory

after_success:
  - if [ "$TYPE" == "coverage" ]; then bash build/travis/uploadCoverage.sh; fi

cache:
  directories:
  - "$HOME/.composer/cache"

notifications:
  email:
    on_success: change
    on_failure: always


