# This file is used in the "dev" and "uat" environments to be able to test future and past campaigns
campaigns:

  address_type_steps:
    active: true
    start: "2022-11-01"
    end: "2023-12-31"
    default_bucket: "direct"

  membership_intervals:
    start: "2023-01-05"
    default_bucket: "all_intervals"
    active: true

  address_pages:
    start: "2023-01-01"
    default_bucket: "legacy"
    active: true

  new_design:
    start: "2023-01-01"
    default_bucket: "new"
    active: true