# This file is used on test server
#
# Set all campaigns to inactive to force the test server to use the default code paths

membership_call_to_action:
  active: true

amount_options:
  active: true
  start: "2018-12-01"

compact_design:
  active: true
  start: "2019-10-06 10:00:00"

address_type:
  active: false
  start: "2020-09-15"

address_provision_options:
  active: true
  start: "2020-09-20"
  default_bucket: "provisional_address_options"