---
- name: Install PHP dependencies
  composer:
    command: install
    working_dir: "{{ build_dir }}"
    no_dev: "{{ composer_no_dev }}"
    optimize_autoloader: "yes"

- name: Install JavaScript dependencies
  npm:
    path: "{{ build_dir }}"

- name: Compile JavaScript
  command: npm run build-js
  args:
    chdir: "{{ build_dir }}"
