# This file is meant to be included from the deployment.yml playbook
# It will create an archive of the source code and all its PHP and JavaScript dependencies
#
# The variable "build_dir" contains the inventory-specific path where all the code is checked out and assembled.
# That path could be deleted between deployments, but for performance reasons the code should stay in place.
# "buil_dir" is passed in from deployment.yml
#
# All other variables come from the inventory file.

- name: Checkout code
  git: repo=https://github.com/wmde/FundraisingFrontend.git dest={{ build_dir }} version={{ build_branch }}

- name: Install PHP dependencies
  composer: command=install working_dir={{ build_dir }} no_dev={{ composer_no_dev }} optimize_autoloader=yes

- name: Install JavaScript dependencies
  npm: path={{ build_dir }}

- name: Build assets
  command: npm run build-assets chdir={{ build_dir }}

- name: Compile JavaScript
  command: npm run build-js chdir={{ build_dir }}

- name: Create tarball
  shell: tar -czf {{ build_dir }}.tar.gz --exclude=".git" --exclude=node_modules -C {{ build_dir }} . warn=no