---
- name: Create a new archive of the fundraising application on the local machine
  hosts: local
  connection: local
  tasks:
    - include: tasks/build.yml
      vars:
        build_dir: "/tmp/fundraising-build-{{ hostvars[inventory_hostname]['inventory_file'] | basename }}"

- name: Deploy the created archive to the server
  hosts: webservers
  vars:
    app_owner: deploy
    app_group: www-data
    keep_releases: 5
  tasks:
    - name: Generate release timestamp
      local_action: command date '+%Y%m%d%H%M%S'
      register: release_timestamp
      delegate_to: 127.0.0.1

    - include: tasks/deploy_to_server.yml
      vars:
        release_name: "{{ release_prefix }}{{ release_timestamp.stdout }}"
        local_archive: "/tmp/fundraising-build-{{ hostvars[inventory_hostname]['inventory_file'] | basename }}.tar.gz"

    - name: Check if the website is reachable
      uri: "url=https://{{ inventory_hostname }}/"
